name: Ngrok RDP Access

on:
  workflow_dispatch:

jobs:
  start-rdp:
    runs-on: windows-latest  

    steps:
      - name: Bật Remote Desktop (RDP)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user user pass123! /add
          net localgroup Administrators user /add

      - name: Cài đặt và chạy Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip -DestinationPath .
          ./ngrok.exe authtoken 2vJGNV47gZqAbDbj0gRQFt18ZJz_4CDQRaYeFngeHkcPLNvv7
          ./ngrok.exe tcp 3389
